apiVersion: v1
kind: Service
metadata:
  name: smart-cooking-api
  labels:
    run: smart-cooking-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: smart-cooking-api
