apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smart-cooking-db
  labels:
    run: smart-cooking-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: smart-cooking-db
    spec:
      containers:
      - name: smart-cooking-db
        image: tarantool/tarantool:1.7
        imagePullPolicy: Always
        ports:
          - containerPort: 3301
